name: E2E Poc
run-name: e2e poc

env:
  DB_USER: postgres
  DB_PASS: postgres
  DB_HOST: localhost
  DB_PORT: 5432
  REDIS_PORT: 6379

on:
  workflow_dispatch:

  pull_request:
    branches:
      - protected

jobs:
  front_build:
    name: "Frontend build"
    runs-on: ubuntu-latest
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
    steps:
      - name: "Checkout the Frontend"
        uses: actions/checkout@v3

      - name: "Use node 18"
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      # - name: "Install front deps"
      #   run: "npm ci"

      # - name: "check resources"
      #   run: "free -h"

      # - name: "Build front"
      #   run: "npm run build"

      # - name: "Run front"
      #   run: "PORT=5173 npm run start &"

      # - name: "Wait for front"
      #   run: "sleep 5"

      # - name: "Validate with curl"
      #   run: "curl localhost:5173"

      - name: "Clone backend"
        run: "cd .. && git clone https://github.com/ElrikSouza/board-api.git"

      - name: Start Redis
        uses: supercharge/redis-github-action@1.7.0

      - name: "Install backend dependencies"
        run: |
          cd ../board-api
          npm install

      - name: "Build backend"
        run: |
          cd ../board-api
          npm run build

      - name: "Run backend"
        run: |
          cd ../board-api
          npm run start &

      - name: "Wait for back"
        run: "sleep 5"

      - name: "Validate with curl"
        run: "curl localhost:3000"
