name: E2E Poc
run-name: e2e poc

on:
  workflow_dispatch:

  pull_request:
    branches:
      - protected

jobs:
  front_build:
    name: "Frontend build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the Frontend"
        uses: actions/checkout@v3

      - name: "Use node 18"
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: "Install front deps"
        run: "npm ci"

      - name: "check resources"
        run: "free -h"

      - name: "Build front"
        run: "yarn build"

      - name: "Run front"
        run: "PORT=5173 yarn start:prod &"

      - name: "Wait for front"
        run: "sleep 5"

      - name: "Validate with curl"
        run: "curl localhost:5173"
